# Generated by Django 5.2.8 on 2025-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career_goal',
            field=models.TextField(blank=True, help_text="Student's career goal or aspiration"),
        ),
    ]
