# Generated by Django 5.2.8 on 2026-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobposting_company_studentprofile_career_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='Awards, certifications, hackathons, etc.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='Projects (suggested: one per line)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated stack, e.g. Python, Django, React', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
